### ISSUE TITLE
Imprecision or error re: <object>?

### ISSUE THREAD

**Issue by fvsch** [designbyjake/svgontheweb#1]
Hi Jake. Thanks for a great resource. :+1: 

The page currently reads:

> `<object>` is pretty much the best option to use if you want to be able to manipulate an SVG.

I'm not sure what you mean by that. The phrase "manipulate an SVG" suggests manipulating the SVG dom or styles from outside the SVG file itself (mostly from the host page, or related stylesheets and scripts). But in my testing there is no need in either Chrome or Firefox to style or access the SVG‘s elements.

This works for Inline SVGs, and for `<svg><use xlink:href="external.svg#symbol-id"></svg>`:

```css
object, svg {
    fill: red;
    stroke: lime;
    stroke-width: 5px;
}
```

Additionnally for external SVG symbols, this would work in Firefox, but it's considered a bug:

```css
svg path {
    fill: lime;
}
```

Returning to `<object>`, this doesn't work either:

```js
document.querySelector('object.bb-logo-example svg'); // null
document.querySelector('object.bb-logo-example path'); // null
```

Did you mean that `<object>` is an interesting option because, unlike the `<img>` tag, it allows the SVG file to run scripts (embedded inside the file) and reference external scripts and stylesheets? (Note I'm not 100 percent sure of which browsers allow what.)
If yes, what would be the differences between using `<object>` for that, and using `<iframe>`?

**Comment by designbyjake** [comment]
@fvsch I’ll look at updating the wording here so it is a little clearer. But yes that is what I am trying to say yes. AFAIK there isn’t much difference between `<object>` and `<iframe>` — I’ll look into the scripting things a little more and get back to you, sorry JavaScript isn’t really my thing so I haven’t dug to far into it.

This link might explain some things a little better? http://stackoverflow.com/questions/5692037/differences-in-using-iframe-and-embed-for-displaying-svg-and-scripting#answer-5693580

**Comment by designbyjake** [comment]
@fvsch I’ve updated the copy and added some more information, I’m going to close this, but please reopen if you still think it is misleading. Thanks.
