### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by cthedot** [designbyjake/svgontheweb#2]
Is there no info about browser support? I saw one note about Safari but nothing that most animations do not work on IE (have not checked Edge). Could you add something about this? Thanks!

**Comment by designbyjake** [comment]
@cthedot good point — I’ll get this added

**Comment by ahite-archermalmo** [comment]
actually you should just add a section called "Fallbacks" which would cover browser support and how to account for that. then it would be solid gold.

**Comment by brianmontana** [comment]
http://caniuse.com/#search=svg Edge will support animations and it's just FF that has problems.

**Comment by designbyjake** [comment]
Browser support + fallback info added.

**Comment by cthedot** [comment]
great, thanks!
