### ISSUE TITLE
Alternative implementation option: Inline SVG with <image>

### ISSUE THREAD

**Issue by aarontgrogg** [designbyjake/svgontheweb#5]
Not an Issue, and didn't want to send as a Commit as it may not fit with the _spirit_ because of the couple minor issues, but thought it was worth mentioning.  Alexey Ten offers a cool implementation option (http://lynn.ru/examples/svg/en.html) which was more deeply discussed and tested by Chris Coyier (https://css-tricks.com/svg-fallbacks/).  Aside from the iOS 3/4 and IE9-11 issues, seems solid to me.

Cheers,
Atg

**Comment by designbyjake** [comment]
@aarontgrogg Cool I hadn’t seen that method, thanks for sharing. I’m not too concerned with fallbacks as  I think we are at a point where we don’t really need to provide them, so I’m not going to add a mention of this. I think there are enough other fallback options in the linked article. 

Thanks, Jake.
