### ISSUE TITLE
Multilingual translation

### ISSUE THREAD

**Issue by janily** [designbyjake/svgontheweb#6]
hi jake
I really like this project.
I want to translate a Chinese version.
Could you add a Chinese version?
Thanks.

**Comment by designbyjake** [comment]
@janily That would be great! If you are happy to start working on the translation, I’ll work on a way we can implement it. Thanks.

**Comment by designbyjake** [comment]
@janily Your translation is now up at https://svgontheweb.com/zh/ — thank you very much!
